### ISSUE TITLE
Website Vorschau nicht konfiguriert

### ISSUE THREAD

**Issue by torbendury** [fridaysforfuture-landau-pfalz/fridaysforfuture-landau-pfalz.github.io#1]
Hallo zusammen,

mehr durch Zufall habe ich gesehen, dass die Website Vorschau bei euch nicht konfiguriert ist.
[Die findet ihr hier](https://github.com/fridaysforfuture-landau-pfalz/fridaysforfuture-landau-pfalz.github.io/blob/c8c9a15b1c9dcbc2d32c73211658ac572e49f74e/_config.yml#L24-L27).

Werden Links eurer Seite z.B. bei Telegram geteilt, erscheint dieser Text als Unterschrift in der Vorschau eurer Website.

**Comment by KlimastreikLandau** [comment]
Danke für den Hinweis. Ich hoffe jetzt klappt es.
